#!/bin/bash
# MetaMask 네트워크 추가 정보

echo "================================================"
echo "  BEGA L2 - MetaMask 네트워크 설정 정보"
echo "================================================"
echo ""
echo "Network Name: BEGA L2"
echo "RPC URL: http://localhost:8545"
echo "Chain ID: 12345678"
echo "Currency Symbol: BEGA"
echo "Block Explorer: (없음 - 로컬 테스트넷)"
echo ""
echo "================================================"
echo "  설정 방법"
echo "================================================"
echo "1. MetaMask 열기"
echo "2. 네트워크 선택 드롭다운 클릭"
echo "3. '네트워크 추가' 클릭"
echo "4. '수동으로 네트워크 추가' 선택"
echo "5. 위 정보 입력"
echo "6. '저장' 클릭"
echo ""
echo "================================================"
echo "  브릿지 사용 방법"
echo "================================================"
echo "L1 (Sepolia)에서 BEGA 토큰을 L2로 입금하려면:"
echo "- OptimismPortal 컨트랙트 사용"
echo "- 배포 완료 후 주소가 제공됩니다"
echo ""
